### PR TITLE
feat!: migrate to microgenerator

### PR DESCRIPTION
**Pull request by busunkim96**
This library has a [manual surface](https://github.com/googleapis/python-trace/tree/master/google/cloud/trace) that calls out to the GAPIC layer. I suspect this is mainly because of when this library was written. See [PR](https://github.com/googleapis/google-cloud-python/pull/3512) for context.

The only added functionality seems to be a stored [`project_id`](https://github.com/googleapis/python-trace/blob/d3f18195e92915289f9d9d5075de1f11eb316353/google/cloud/trace/v1/client.py#L159-L160). This PR _removes_ the handwritten layer since the costs of maintaining that handwritten layer seem greater than the benefits. The addition of proto plus makes the other helpers ([dict to protobuf](https://github.com/googleapis/python-trace/blob/master/google/cloud/trace/_gapic.py#L240) and [datetime conversion](https://github.com/googleapis/python-trace/blob/d3f18195e92915289f9d9d5075de1f11eb316353/google/cloud/trace/v1/client.py#L162-L166)) obsolete.

There is a directory of samples written against the new surface to help folks who were using the manual wrapper adjust their code.

CC @simonz130 and @daniel-sanche since this is one of the Stackdriver libraries.

### CODE REVIEW

**Comment by busunkim96** [comment]
I borked the repo name in the kokoro config 😆. Will re-run shortly.

**Comment by Daniel-Sanche** [comment]
> This PR removes the handwritten layer since the costs of maintaining that handwritten layer seem greater than the benefits

I believe the long term plan is for our team to eventually update and maintain the handwritten libraries for this. It _may_ be worthwhile keeping the existing API surface around instead of forcing customers to switch back and forth

That being said, I don't think Trace is going to be on our radar for a while. And I'm not familiar with the library, so I'd have to do some digging to see if the existing hand-written part is even worth keeping. It looks pretty light weight. I'd probably prefer to go fully auto-generated for now and re-assess later if the customer impact isn't too high. What do you think @simonz130?

**Comment by busunkim96** [comment]
I think it's uncommon for folks to interact with this library directly. It looks like the docs push folks to interact with the Trace API via OpenCensus or OpenTelemetry.

https://cloud.google.com/trace/docs/client-libraries

> For your application to submit traces to Cloud Trace, it must be instrumented. You can instrument your code by using the Google client libraries. However, it's recommended that you use OpenTelemetry or OpenCensus to instrument your application. These are open source tracing packages. OpenTelemetry is actively in development and is the preferred package.

The OpenCensus StackDriver Trace Exporter declares `google-cloud-trace` as a dependency. https://github.com/census-instrumentation/opencensus-python/blob/862885af8081dc3ede50d1df4a28e4400c22e8f8/contrib/opencensus-ext-stackdriver/setup.py#L43

**Comment by simonz130** [comment]
We should trim the manual layer from this library and make a major release as a result. We should focus on steering folks to use OT exporter instead of this library directly.

**Review by Daniel-Sanche — APPROVED** [review]
Yeah, that makes sense to me

**Comment by busunkim96** [comment]
Thanks @simonz130 @Daniel-Sanche! I'll cut a release on Monday.

**Comment by kintel** [comment]
Thanks for getting this done. I've pinged the Cloud Trace team in case they want to follow up, but it looks great!

**Pull request merged**
